### PR TITLE
Helm Chart files are added for i2i 5G Core products

### PR DESCRIPTION
**Pull request by hasankose86**

### CODE REVIEW

**Comment by jsm84** [comment]
@hasankose86 I believe you need the base64 encoding of the actual GPG public key in the owners file (not the encoding of the sha256 digest of the key).

I'm not certain if the base64 encoding needs the `BEGIN/END PGP KEY BLOCK` header/footer, respectively, but I would run the sha256sum against the key block until it matches what's in the `report.yaml`. Then use the base64 encoding of that in the `OWNERS` file.

**Comment by jsm84** [comment]
@hasankose86 Thanks for your persistence here. I've been looking at the GHA code as well, trying to see what is going on behind the scenes.

What you've attached previously in the project settings (base64 encoded public key) looked good, but still wasn't matching against the report.yaml.

Have you tried removing base64 encoding? Try simply putting the public key block into the project settings. I'm not seeing where base64 is being accounted for in the code base, so the docs could simply be incorrect or outdated.

**Comment by jsm84** [comment]
@hasankose86 I'm seeing in the project settings the encoded digest value again...

Are you doing this base64 conversion yourself? What are you pasting into the project settings in Red Hat Partner Connect?

can you share that, please? I'm curious to see where/how this base64 conversion is occurring.

**Comment by hasankose86** [comment]
> 

Hi @jsm84 ,

I specified my steps in below. Please inform me , if there are any false.

1-  I created public key and secret key as below;
      -  gpg --generate-key 
      - gpg --export >~/.gnupg/pubring.gpg  
      - gpg --export-secret-keys >~/.gnupg/secring.gpg 
      
2- I signed my chart with secret key.
    - helm package --sign --key "i2i5gcore" --keyring ~/.gnupg/secring.gpg src

3- I saw that .tgz and .tgz.prov  files created

4- I exported my public key with armor
     - gpg --armor --export i2i5gcore > public.key
    
5-  I run chart-verifier tool with public key . I saw that the report was generated
    - ./chart-verifier verify i2i5gcorehelm-1.0.0.tgz    --pgp-public-key=public.key

6- I pasted public.key to settings in Red Hat Partner Connect.

Thanks

**Comment by jsm84** [comment]
@hasankose86 Ok a few of us engineers got together today and figured out how the public key digest is hashed on both sides (by `chart-verifier` and by the GHA workflow that's been failing here).

The public key is encoded to base64 _before_ the sha256 hash is computed on both sides (in GHA and in `chart-verifier`).

I was able to extract your public key from the partner API (from a previous run) and get a matched digest by running:

```
$ echo $(base64 -w0 public_gpg.key) | sha256sum
d6a5496f8b9e3ecff01efb43420f128b4d9239e8633b6686865fd16a6223c678  -
```

This matches what is pulled out of the `OWNERS` file (generated by the field in RHPC project settings) in this run: https://github.com/openshift-helm-charts/charts/actions/runs/5132073862/jobs/9232917995?pr=872#step:23:28

```
[INFO] digest of PGP key from OWNERS :d6a5496f8b9e3ecff01efb43420f128b4d9239e8633b6686865fd16a6223c678:
```

So... using this same keypair (or by creating a new one... you technically leaked your private key by pasting it into the RHPC project field), you should paste the raw public key contents into the RHPC project field after checking the result of this command against what is in the `report.yaml` file, to make sure that it matches:

```
$ echo $(base64 -w0 public.key) | sha256sum
```

Please give this a try and let us know if you need further help.

**Comment by hasankose86** [comment]
Hi @jsm84 

Thanks for your reply,

I have tried as you specified. You can find as below;

$ cat chartverifier/report.yaml | grep publicKey
            publicKey: c3e7c51547e40ce879a5c1c245149583751b4fa19b624bfd360f783ff80528e4

$ echo $(base64 -w0 public.key) | sha256sum
c3e7c51547e40ce879a5c1c245149583751b4fa19b624bfd360f783ff80528e4  -

But when i pasted raw public key to RHPC project, i saw digest of PGP key in OWNERS file as below ;

[INFO] digest of PGP key from OWNERS :a05fc41367124454eb52844ce27b736a8ce29ce51e23b564fe7e59e1bc4fa95a:

I still did not understand what i should past as public key to RHPC project page.

Thanks

**Comment by jsm84** [comment]
Hi @hasankose86 and thanks again for the update.

What we're seeing in Connect right now is _double_ encoded into base64. Once we decode it once (stripping the extra layer of encoding) we get the exact same public key digest that you've provided above.

Sorry for the confusion, but I tried to communicate that the base64 happens automatically.

All you need to do is paste the raw key text (no extra whitespace) into Connect, and you should be good to go.

This is what you should be pasting into Connect:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBGR2LtsBCACppHBQAplb/TvfefoXS69FAsjarmuEtgrrhiVNhPqh/t0tMnh/
8C+yIMqcug3zcRvLIBm21a8yBho6WT91WKR90g33GyqwIVrKs8aXdmHpbUfyphwC
Ndk86GVZk9v3mxmZwDudgFFV/gQk+EqFoWdlcp32ihzTvWFxcaTWLg5pjt1kLedL
ArlKpVSDLZQoRgbkhHhmyqj/kiflhj1qu7iPmbNVytndS+9y1Xuy3NO/YZWzeQ5+
Yex1/EGUI7hDEDR0lrhu6mBSsdoqpv63VAGp+ENhJ8OkBdZY9bBtn1iq242j1qJi
ApkH2snPMOGoKZi4XRq9gmy19J2589D5Qc4lABEBAAG0CWkyaTVnY29yZYkBVAQT
AQgAPhYhBDrXymkRpRfVA92oMNBR7rbMq2hNBQJkdi7bAhsDBQkDwmcABQsJCAcC
BhUKCQgLAgQWAgMBAh4BAheAAAoJENBR7rbMq2hNHFUH/AyT0GtCac8v1OUjmUNZ
IzFXbo9998gWLUiizduJ1hm9UfYmxiN2JFpwhw7zSkcapX8A/K8lw85GXvUWSKwA
m5mOyaViEkmkzt2LStLMT93znP51dRTRd1Ho1ZlE0F31u9kcbgLT756qHLAszd84
bW5E1K4pewGggPb4wlc388Cd1pUwOO2oBkutW8sSGUTjJ68zXG9NvCwbzSW7SkMJ
FMbSsSsnA17inXO3Y/rwYgirNl5Inofz1Ss+ThoOv9mC2zO+beftASRU18QoGWGu
uAmGR9aOtljxjQkas+ZlzaolH15wAOoaaJUJM+kXYL5F+aGrVFo0l+owUZZjXkm0
HGO5AQ0EZHYu2wEIAMIv1E1jq9KCVCfoypi9hXTsrhQHwwuBN51zII4Vxobj/td8
8MLAOQMt40bXPB2k44tZkCVJANpj2MZ8mSe8FiZuTBa+asV4p6v14n4EaKX+mUVH
YCdABhGp8X4pUBbQLW72Q6VlRrQ2GuNOKx3Vu9PC32BXF1Y42+YoEt+Ar58R80+v
O00f/NarzMv37uU8MC5gGBKZX/9XnvRqeZ+kyaGAaEwVVQ92PfWJdhSCf7XLMz13
ALY2gxFTK4H1U2l4rIoilr8eL+ykTSmwicWqxMZAYXYCLIaPJ3igvUkZttBpE0nY
b7RjXl210a+JrGBRxgACiQip1hjVuSfz55epZmUAEQEAAYkBPAQYAQgAJhYhBDrX
ymkRpRfVA92oMNBR7rbMq2hNBQJkdi7bAhsMBQkDwmcAAAoJENBR7rbMq2hNmNIH
/iLHlFCBNZ8Zo7egPoBUTg7niZU/BnP275NjiRn8zWtvFxK0R6jxSEwK46VBB+yO
eYltDXdg+GqwfqstzqEsadoIumUWm5Ri+KW5vvreb8VVor1iQhcarwnT32jsvNEb
GmhlNDntm4Xxm1TPLrFEKv56Hd8Vlkx8+KcZQIFx2Az3Ha9+WADCs+0q3Ue8hfV/
BkZ1aPzeCfcT1D7LROnWMfiGBm+UPLZd9htwnasPs7K5Nt1lEj36TSU847KlrP6S
lfyqsyfqp1jfg+6/IGPnkcbC0E0vWw8fRH0pOqPVsyWC36ZaFUURgSobcbDoe50L
SDZ48Khe2zZhz93lpf5ksK0=
=lOkS
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by jsm84** [comment]
Hi @hasankose86, I brought up this topic in this morning's stand up call, and @komish has done further ground work to figure out what happened here.

You accidentally skipped a leading hyphen on the header line, when copying & pasting this into Connect:

 `----BEGIN PGP PUBLIC KEY BLOCK-----` (only 4 hyphens instead of 5), enough to completely change the digest value.
 
 We've confirmed that adding this hyphen gives us the correct sha256 digest value.

**Comment by komish** [comment]
@hasankose86 The latest issue you're seeing is because you've provided a report-only submission. Please see the troubleshooting doc here: https://github.com/redhat-certification/chart-verifier/blob/main/docs/helm-chart-troubleshooting.md#the-chart-uri-is-not-a-valid-url. You need to provide a URL as your chart URI when generating your report.

**Comment by hasankose86** [comment]
Hi @jsm84  

İ could pass step of match digest.

Thanks

**Pull request merged**
