### PR TITLE
Added helm chart verification report

### PR DESCRIPTION
**Pull request by Digitalpit**
Added helm chart verification report

### CODE REVIEW

**Comment by Digitalpit** [comment]
Chart is stored in our internal repo and it's not accessible for everyone (only whitelisted IPs)
I created this project in RedHat site like this, so should be fine:
image
Please advice

**Comment by mgoerens** [comment]
@Digitalpit In your case, you need to run the report with the `--web-catalog-only` flag. See https://github.com/redhat-certification/chart-verifier/blob/main/docs/helm-chart-submission.md#web-catalog-only

Hope that helps !

**Comment by Digitalpit** [comment]
So I need to create project for helm chart from scratch to be able to fix it?

**Comment by mgoerens** [comment]
Yes, unfortunately those settings cannot be modified, hence you need to create a new Helm Chart certification project.

Please see: https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/helm-chart-certification/creating-a-helm-chart-certification-project

For the distribution method you'll need to select "Web Catalog Only" as you are hosting the Helm Chart in a private repository.

**Pull request closed without merging**
