### PR TITLE
charts 2.2.6

### PR DESCRIPTION
**Pull request by Bhagyashreek8**

### CODE REVIEW

**Comment by Bhagyashreek8** [comment]
Can someone help with the failing check on this PR, chart verifier install is failing.

**Comment by Bhagyashreek8** [comment]
Need help with fixing the check , it is failing in installing chart verifier.

**Comment by ambiknai** [comment]
This can be closed as new PR got merged https://github.com/openshift-helm-charts/charts/pull/659

**Comment by mmulholla** [comment]
Closing PR as requested

**Pull request closed without merging**
