### PR TITLE
Add Infinispan chart

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by zonggen** [comment]
Thank you for submitting the chart! The script was expecting the chart name to be `infinispan-helm-charts`. Therefore the path should be
```diff
- charts/community/infinispan/infinispan/0.1.0
+ charts/community/infinispan/infinispan-helm-charts/0.1.0
```
and the tarball to be
```diff
- infinispan-0.1.0.tgz
+ infinispan-helm-charts-0.1.0.tgz
```

The reason behind this is the script is respecting the name defined in the `Chart.yaml` which is `infinispan-helm-charts`. Running `helm package infinispan-helm-charts/` also generates `infinispan-helm-charts-0.1.0.tgz`.

**Comment by ryanemerson** [comment]
@zonggen Thanks for explaining. I have updated the chart name to simply "infinispan".

**Comment by dperaza4dustbit** [comment]
Hello @ryanemerson do you want to take a look at why the testing is failing?

**Comment by ryanemerson** [comment]
> Hello @ryanemerson do you want to take a look at why the testing is failing?

@dperaza4dustbit The cause isn't obvious to me. AFAICT the only checks that failed are ones that have `type: Optional`.

**Comment by dperaza4dustbit** [comment]
@ryanemerson yeah it is not blocking the PR just want to give you a chance to debug before it make the repo.

**Comment by ryanemerson** [comment]
I think the failures are fine:

- `images-are-certified` - It's upstream so we can't fix this.
- `has-kubeversion` - The Chart should work with all Openshift versions that have Helm chart support. I will make a note to add this in the future though.
- `chart-testing` - I don't know what this is TBH, any ideas?

**Review by dperaza4dustbit — APPROVED** [review]

**Comment by dperaza4dustbit** [comment]
@ryanemerson we fixed an issue in the publishing flow, if you rebase I can publish this

**Comment by dperaza4dustbit** [comment]
> I think the failures are fine:
> 
> * `images-are-certified` - It's upstream so we can't fix this.
> * `has-kubeversion` - The Chart should work with all Openshift versions that have Helm chart support. I will make a note to add this in the future though.
> * `chart-testing` - I don't know what this is TBH, any ideas?

You can add test cases to a chart the can be executed after a chart has been installed: https://helm.sh/docs/topics/chart_tests/

**Pull request merged**
