### PR TITLE
HashiCorp Vault 0.12.0

### PR DESCRIPTION
**Pull request by tvoran**
https://github.com/hashicorp/vault-helm/releases/tag/v0.12.0

### CODE REVIEW

**Comment by tvoran** [comment]
For what it's worth, this passes in crc 1.26.0+31f06c09 locally for me:

```console
vault/0.12.0/src on  vault-0.12.0 ⛵ crc-admin (default)
❯ chart-verifier verify .                                                
apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        chart-uri: .
        digest: sha256:ec2c09a0e5994ddb5014eea3db3c8bce41166ffa91471a06101890c6b39df36e
        lastCertifiedTimestamp: "2021-06-15T16:16:31.832818-07:00"
        certifiedOpenShiftVersions: 4.7.0
    chart:
        name: vault
        home: https://www.vaultproject.io
        sources:
          - https://github.com/hashicorp/vault
          - https://github.com/hashicorp/vault-helm
          - https://github.com/hashicorp/vault-k8s
          - https://github.com/hashicorp/vault-csi-provider
        version: 0.12.0
        description: Official HashiCorp Vault Chart
        keywords:
          - vault
          - security
          - encryption
          - secrets
          - management
          - automation
          - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.7.2
        deprecated: false
        annotations: {}
        kubeversion: '>= 1.14.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
  - check: contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: chart-testing
    type: Mandatory
    outcome: PASS
    reason: Chart tests have passed
  - check: has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.10.1-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.7.2-ubi

```

**Comment by baijum** [comment]
The error message in the comment is a bit misleading. The console shows the `chart-testing` check has failed:
```
  - check: chart-testing
    type: Mandatory
    outcome: FAIL
    reason: |-
        Error running process: executing helm with args "install vault-m4xcyzbalc /root/.cache/chart-verifier/_charts/vault --namespace chart-verifier-ci-openshift-helm-charts-charts-200 --wait --values /tmp/chart-testing-120125852/values.yaml": exit status 1
        ---
        Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: clusterrolebindings.rbac.authorization.k8s.io "vault-m4xcyzbalc-agent-injector-binding" is forbidden: User "system:serviceaccount:chart-verifier-ci-openshift-helm-charts-charts-200:chart-verifier-ci-openshift-helm-charts-charts-200" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

When chart-testing is failed, the `certifiedOpenShiftVersions` value is coming as an empty string.
I have reported it here: https://github.com/redhat-certification/chart-verifier/issues/157

The check is failed as the test environment has restricted access to `clusterrolebindings`.
@dperaza4dustbit @mmulholla @rhrivero Can you please confirm if we can allow access to `clusterrolebindings` ?

**Comment by baijum** [comment]
I have created another PR to prioritize report verification above the certifiedOpenShiftVersions. This way user will see the report-related errors first.

https://github.com/openshift-helm-charts/charts/pull/201

cc. @mmulholla

**Comment by slemeur** [comment]
> @dperaza4dustbit @mmulholla @rhrivero Can you please confirm if we can allow access to clusterrolebindings ?

Let's go for it.

**Comment by dperaza4dustbit** [comment]
Thanks Harshicorp for this PR, we are looking forward to working with you to make your chart OpenShift certified. Let me explain here a bit for the sake of transparency. For our test cluster we use sa account that is only allowing namespace level resources to be created. Looking at you PR it does look like you will need some Resources at the Cluster level which will required an Identity/role with cluster level authorities. Two questions?

1. Is it possible to scope down the permission required to run this chart to a namespace level?
2. Even if it is possible, is it a deployment pattern you would recommend your customers to use? Why or Why not?

**Comment by tvoran** [comment]
Hi @dperaza4dustbit, so the chart as submitted has two components enabled (vault server and the vault-k8s secrets injector) and they both have cluster role/binding's included.

The injector uses a cluster role/binding to manage its mutating webhook and it's intended to work across all namespaces. So we would need to disable the injector component entirely to pass the test here.

The server sets up a cluster role/binding to aid in the verification of service account JWTs with the Kubernetes auth method in Vault. We can disable just this part of the server component, but that will make it more difficult for users to configure that particular auth method.

So I think we can change the chart options to omit the cluster role/binding's, but I'll have to check with the team here to see if that's a recommended deployment configuration.

**Comment by dperaza4dustbit** [comment]
@tvoran thanks for the response, it makes sense. We both want the best experience for the OpenShift customers. So keep that in mind as the main objective here. While you check with your team we are exploring what is the most granular way that we can enable this permission in our certification test cluster. Will keep you posted here.

**Comment by dperaza4dustbit** [comment]
https://github.com/openshift-helm-charts/charts/pull/202 adds the permissions you need. I tried to add specifically what is needed, please review. BTW, does it make sense to add a section in the Readme indicating the Rules that will be required to be able to install this chart?

**Comment by tvoran** [comment]
Thanks! #202 looks correct to me, and we'll look into updating our docs around requirements.

**Comment by mmulholla** [comment]
@tvoran we are ready to re-run builds. Can wait on your README update or re-run without. Please let me know which option you prefer.

**Comment by tvoran** [comment]
@mmulholla Please go ahead and rerun without, thanks.

**Comment by mmulholla** [comment]
@tvoran sorry, that did not work, need to rebase the branch in the PR onto the latest main

**Comment by mmulholla** [comment]
Whoo hoo - its merged!!!

**Comment by acahn** [comment]
Thank you Martin!

**Comment by tvoran** [comment]
Thanks folks!

**Pull request merged**
