### PR TITLE
Add chatbot-ai-sample 0.1.1

### PR DESCRIPTION
**Pull request by thepetk**
The PR adds the first version of the `chatbot-ai-sample` (0.1.1).

The repository for the source code of this helm chart is here: https://github.com/openshift-helm-charts/charts

It also includes the report.yaml ran for the `community` vendorType

### CODE REVIEW

**Review by elsony — APPROVED** [review]
lgtm

**Comment by thepetk** [comment]
On hold until a new report.yaml is uploaded containing a successful helm-testing check.

**Comment by thepetk** [comment]
> On hold until a new report.yaml is uploaded containing a successful charts-testing check.

I've updated the content of the PR with a report including a successful run for charts-testing.

**Review by komish — APPROVED** [review]
/lgtm

**Pull request merged**
