### PR TITLE
Rename spring-boot-rest-http to redhat-springboot-rest

### PR DESCRIPTION
**Pull request by Sgitario**
As per action requested email from Josh.

### CODE REVIEW

**Comment by Sgitario** [comment]
cc @jsm84

**Comment by jsm84** [comment]
@Sgitario The name change looks good, but (something I neglected to mention) as part of the index rollout, we're not fixing old chart releases as we can't "re-release" those.

The fix here is to create a new chart release version, either 0.0.2 or 0.0.1+1 (hyphenated tags won't get picked up by helm as the latest release version). You can leave the 0.0.1 chart release as is.

**Comment by jsm84** [comment]
I should also add that the chart release needs it's own separate PR (from the chart directory and OWNERS file name changes), or I can submit the directory change separately and you can rebase.

**Comment by Sgitario** [comment]
> I should also add that the chart release needs it's own separate PR (from the chart directory and OWNERS file name changes), or I can submit the directory change separately and you can rebase.

So, this PR to add the OWNERS file, and https://github.com/openshift-helm-charts/charts/pull/1273 to add the chart (I will rebase it once this is merged)

**Review by jsm84 — APPROVED** [review]
lgtm

**Pull request merged**
