### PR TITLE
Added chart pubsubplus-openshift-3.0.0

### PR DESCRIPTION
**Pull request by bczoma**

### CODE REVIEW

**Comment by mmulholla** [comment]
Apologies, this failed because we are in the middle of an update. Will restart the build once we are complete.

**Comment by bczoma** [comment]
Oh @mmulholla , thank you very much for your comment. Was scratching head what I did wrong. No problem, waiting. - Balazs

**Comment by mmulholla** [comment]
@bczoma have restarted the build.

**Comment by mmulholla** [comment]
@bczoma sorry, have yo ask you to rebase on latest main branch and push the update.

**Pull request merged**
