### PR TITLE
Add YugabyteDB Anywhere (yugaware) 2.14.4 chart

### PR DESCRIPTION
**Pull request by bhavin192**

### CODE REVIEW

**Comment by mmulholla** [comment]
@bhavin192 due to a bug in the way we create OWNERS files the OWNERS file includes  ```providerDelivery: true``` but it should have been set to false. 
Please confirm that you do not intend to use the provider delivery control feature and I will correct your OWNERS file. You will then need to rebase your branch a resubmit the PR.

**Comment by bhavin192** [comment]
@mmulholla yes, can you please make it `providerDelivery: false`. I was wondering what did I do on the partner portal which might have toggled it, but your reply explains what happened. Thanks in advance.

**Comment by mmulholla** [comment]
@bhavin192 have a PR to update OWNERS file, will let you know when it is merged: https://github.com/openshift-helm-charts/charts/pull/618

**Comment by mmulholla** [comment]
@bhavin192 #618 is now merged. Please rebase your branch and resubmit. Sorry for the inconvenience.

**Pull request merged**
