### PR TITLE
Rename datagrid chart to data-grid

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by ryanemerson** [comment]
@dperaza4dustbit Can we expedite this PR? I need this merged in order to be able to issue a PR for Data Grid 8.3 which has just been released.

**Comment by dperaza4dustbit** [comment]
@ryanemerson if you rename on the path, you will need to rename on the file to

**Comment by ryanemerson** [comment]
@dperaza4dustbit Makes sense. Updated, thanks.

**Review by dperaza4dustbit — APPROVED** [review]
lgtm

**Pull request merged**
